language: ruby
rvm: 2.3.0
node_js: 7

branches:
  only:
    - master

env:
  - JEKYLL_ENV=production

install:
  - gem install jekyll
  - bundle install
  - npm install -g firebase-tools

script: bundle exec jekyll build

after_success:
  - firebase deploy --token $FIREBASE_TOKEN
