language: ruby
rvm: 2.6.3

branches:
  only:
    - master

notifications:
  email: false

env:
  - JEKYLL_ENV=production

install:
  - nvm install 8
  - gem install jekyll
  - bundle install
  - npm install -g firebase-tools

script: bundle exec jekyll build && firebase deploy --token $FIREBASE_TOKEN --non-interactive
