title: Danderyds gymnasium
short_title: Dagy

analytics_id: UA-22710728-1
map_api_key: AIzaSyC4jgcxxVkfMlOyyB_elm4qrdu12YgvEYc

instagram: danderyds.gymnasium
facebook: dandgym

address: Rinkebyvägen 4, 182 36 Danderyd
position:
  lat: 59.4151194
  lng: 18.0423185
email: dagy.info@danderyd.se
phone: 08-568 913 01
public_transport: |
  Buss: 602, 604, 611, 613
  Roslagsbanan: Djursholms Ekeby Station

footer_menu_title: Intranät
footer_menu:
  - title: Portalen
    url: https://portal.danderyd.se
  - title: Schoolsoft
    url: https://sms.schoolsoft.se/danderyd

